---
- name: test the function of ansible-navigator on host
  hosts: lenovo-sr950-02.lab.eng.pek2.redhat.com
  gather_facts: yes
  tasks:
  - name: Print facts
    ansible.builtin.debug:
      msg: '{{ ansible_facts }}'  
