---
- name: test the function of ansible-navigator on host
  hosts: lenovo-sr950-02.lab.eng.pek2.redhat.com
  gather_facts: yes
  become: yes
  tasks:
    - name: Get the status of libvirtd.service
      ansible.builtin.systemd:
        name: "libvirtd"
      register:  libvirtd_status

    - name: Show the status of libvirtd
      ansible.builtin.debug:
        var: libvirtd_status

    - name: Start libvirtd-tcp.socket when libvirtd is inactive
      ansible.builtin.service:
        name: libvirtd-tcp.socket
        state: started
      when:
        libvirtd_status['status']['ActiveState'] == 'inactive'

