---
  - name: deploy chrony.conf template
    ansible.builtin.lineinfile:
     dest: /etc/chrony.conf
     line: "server 10.11.160.238 iburst"
     owner: root
     group: root
     mode: 0644
     backup: yes

  - name: set the timezone to Asia/Shanghai
    community.general.timezone:
      name: Asia/Shanghai

  - name: Restart chronyd
    ansible.builtin.service:
      name: chronyd
      state: restarted
